 # >>! Purpose
Covid_Data.csv contains data from dates 2020-02-29(February) - 2020-08-06(August). 
The intention is to create a program that separates out each state into its own dataframe, 
clean each new dataframe and analyze the data with the best graphs to show trends in the data.
Hopefully the final result will be a Large line graph with 55(count of state's data
including territories) lines that represent the increase of positive cases from February to August.

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [4]:
deathsByState=pd.read_csv("/Users/Jen/Desktop/GWU/GWU-Project-1/data_resources/Covid_Data.csv")

In [5]:
deathsByState

,date,state,positive,negative,pending,hospitalizedCurrently,hospitalizedCumulative,inIcuCurrently,inIcuCumulative,onVentilatorCurrently,...,posNeg,deathIncrease,hospitalizedIncrease,hash,commercialScore,negativeRegularScore,negativeScore,positiveScore,score,grade
0,20200806,AK,4223.0,257349.0,NaN,42.0,NaN,NaN,NaN,2.0,...,261572,0,0,cb6042a57c94293675b4f8b2a02af69d8012d91f,0,0,0,0,0,NaN
1,20200806,AL,96592.0,643192.0,NaN,1575.0,11313.0,NaN,1211.0,NaN,...,739784,19,213,27774ad0a8fd9899b54fb5d577b1b778d3d5004f,0,0,0,0,0,NaN
2,20200806,AR,47028.0,492808.0,NaN,514.0,3118.0,NaN,NaN,111.0,...,539836,7,0,1188e9bb4b25b98410580729c252181b8d1f4dfc,0,0,0,0,0,NaN
3,20200806,AS,0.0,1396.0,NaN,NaN,NaN,NaN,NaN,NaN,...,1396,0,0,5c33616b07ca7687fdea8c9ea6a110cb6abea724,0,0,0,0,0,NaN
4,20200806,AZ,183647.0,812217.0,NaN,1879.0,14068.0,593.0,NaN,427.0,...,995864,70,509,b9e494d4ce7ec7f1188ac5a7b72643b596000d1d,0,0,0,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8636,20200126,WA,2.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,...,2,0,0,7acb526e14f20a29cc74a0b32a37328bc6eac6c2,0,0,0,0,0,NaN
8637,20200125,WA,2.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,...,2,0,0,9b52ca94dd2a996822542ea5f17a7363e7ad91cf,0,0,0,0,0,NaN
8638,20200124,WA,2.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,...,2,0,0,094154f68e74bfc30b977cdee888f9c07be4360e,0,0,0,0,0,NaN
8639,20200123,WA,2.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,...,2,0,0,e16af2a6a8f060355ff5ba499a28309a262c0b1e,0,0,0,0,0,NaN
8640,20200122,WA,2.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,...,2,0,0,8f8db794931706272489cddd51e917a4a69c8c9b,0,0,0,0,0,NaN

In [6]:
deathsByState_drop = deathsByState.head(55)

In [7]:
deathsByState_drop

,date,state,positive,negative,pending,hospitalizedCurrently,hospitalizedCumulative,inIcuCurrently,inIcuCumulative,onVentilatorCurrently,...,posNeg,deathIncrease,hospitalizedIncrease,hash,commercialScore,negativeRegularScore,negativeScore,positiveScore,score,grade
0,20200806,AK,4223.0,257349.0,NaN,42.0,NaN,NaN,NaN,2.0,...,261572,0,0,cb6042a57c94293675b4f8b2a02af69d8012d91f,0,0,0,0,0,NaN
1,20200806,AL,96592.0,643192.0,NaN,1575.0,11313.0,NaN,1211.0,NaN,...,739784,19,213,27774ad0a8fd9899b54fb5d577b1b778d3d5004f,0,0,0,0,0,NaN
2,20200806,AR,47028.0,492808.0,NaN,514.0,3118.0,NaN,NaN,111.0,...,539836,7,0,1188e9bb4b25b98410580729c252181b8d1f4dfc,0,0,0,0,0,NaN
3,20200806,AS,0.0,1396.0,NaN,NaN,NaN,NaN,NaN,NaN,...,1396,0,0,5c33616b07ca7687fdea8c9ea6a110cb6abea724,0,0,0,0,0,NaN
4,20200806,AZ,183647.0,812217.0,NaN,1879.0,14068.0,593.0,NaN,427.0,...,995864,70,509,b9e494d4ce7ec7f1188ac5a7b72643b596000d1d,0,0,0,0,0,NaN
5,20200806,CA,529980.0,7970483.0,NaN,7485.0,NaN,2026.0,NaN,NaN,...,8500463,166,0,04d0f37534059d04347fd2c84c1183d80fe86371,0,0,0,0,0,NaN
6,20200806,CO,48988.0,516331.0,NaN,320.0,6536.0,NaN,NaN,NaN,...,565319,7,20,dd0a6e7ae6aa27e6dcb28e777e72f80bf03badb8,0,0,0,0,0,NaN
7,20200806,CT,50245.0,806853.0,NaN,66.0,10920.0,NaN,NaN,NaN,...,857098,0,113,d79a9001214fc39d2f951554a8120b2eea8ff6ee,0,0,0,0,0,NaN
8,20200806,DC,12518.0,193465.0,NaN,98.0,NaN,23.0,NaN,12.0,...,205983,0,0,b0d8dcc3f5b6f521b29449d8396b809603b7d431,0,0,0,0,0,NaN
9,20200806,DE,15365.0,177338.0,NaN,45.0,NaN,15.0,NaN,NaN,...,192703,0,0,2d3387563566ed83961633acb70ae6940f8d906b,0,0,0,0,0,NaN
10,20200806,FL,510389.0,3346974.0,3325.0,7459.0,29515.0,NaN,NaN,NaN,...,3857363,120,559,5133c0415f2ad100e70476139a8b9e436006f4b6,0,0,0,0,0,NaN
11,20200806,GA,204895.0,1519867.0,NaN,3006.0,20002.0,NaN,3647.0,NaN,...,1724762,42,214,2415a57a39209126158d0a46bc9cc2e08923b937,0,0,0,0,0,NaN
12,20200806,GU,397.0,23480.0,NaN,3.0,NaN,NaN,NaN,NaN,...,23877,0,0,53643c2efe301131079f6fbbac7bf30ca0e07324,0,0,0,0,0,NaN
13,20200806,HI,2763.0,132146.0,NaN,83.0,214.0,15.0,NaN,13.0,...,134909,0,6,602ebbe9f1bdaccb796686e755eb363c6b2f1d1b,0,0,0,0,0,NaN
14,20200806,IA,47361.0,455759.0,NaN,237.0,NaN,68.0,NaN,32.0,...,503120,9,0,4d47289d2091705029bbb261108305358e0eb55c,0,0,0,0,0,NaN
15,20200806,ID,22707.0,171886.0,NaN,242.0,931.0,42.0,262.0,NaN,...,194593,7,25,c93b8e106c05daf70e668410bce185f6d64dd6f3,0,0,0,0,0,NaN
16,20200806,IL,189705.0,2749325.0,NaN,1517.0,NaN,346.0,NaN,132.0,...,2939030,21,0,a9c64c6994d704faed7c63ded6caa5b644c40672,0,0,0,0,0,NaN
17,20200806,IN,71015.0,733330.0,NaN,1009.0,9267.0,301.0,1923.0,82.0,...,804345,6,119,9bf36e773e318b92e0ef5a90808989e9e8aa63e0,0,0,0,0,0,NaN
18,20200806,KS,29717.0,279001.0,NaN,358.0,1821.0,78.0,516.0,25.0,...,308718,0,0,676ce44ff8dd4c7b3dde9478c42d3c530221feea,0,0,0,0,0,NaN
19,20200806,KY,33254.0,599190.0,NaN,701.0,3924.0,140.0,1248.0,NaN,...,632444,8,21,9896e4659d8b3ce61330978a96bc158684ec1657,0,0,0,0,0,NaN
20,20200806,LA,127246.0,1357726.0,NaN,1457.0,NaN,NaN,NaN,215.0,...,1484972,50,0,d86e847ba82d344d549a60f0fc12fd74c929b232,0,0,0,0,0,NaN
21,20200806,MA,119874.0,1151344.0,NaN,403.0,12007.0,73.0,NaN,32.0,...,1271218,32,14,52acc0a4a686e2538f7830baf63161492bc94650,0,0,0,0,0,NaN
22,20200806,MD,93005.0,899136.0,NaN,535.0,12978.0,139.0,NaN,NaN,...,992141,15,56,dae19591906f13dabae5dbba6fee487702db6cc8,0,0,0,0,0,NaN
23,20200806,ME,3997.0,176919.0,NaN,11.0,390.0,3.0,NaN,1.0,...,180916,0,0,ceb7e372643ce1bfd4d4386bba434b65611c1a19,0,0,0,0,0,NaN
24,20200806,MI,94656.0,1911922.0,NaN,694.0,NaN,232.0,NaN,132.0,...,2006578,28,0,83205fa0ec1254dd5e3517f4cd7308712d32f282,0,0,0,0,0,NaN
25,20200806,MN,58640.0,840840.0,NaN,319.0,5421.0,153.0,1583.0,NaN,...,899480,7,48,7a14fe34a8cee72e865e51367aa7f32757a4c52c,0,0,0,0,0,NaN
26,20200806,MO,56383.0,685928.0,NaN,966.0,NaN,NaN,NaN,110.0,...,742311,8,0,84b86300e0af2c9c6f4a5b4211d058a042e9e317,0,0,0,0,0,NaN
27,20200806,MP,47.0,12254.0,NaN,NaN,4.0,NaN,NaN,NaN,...,12301,0,0,dc342afed04e1968a9f90be2e4f19cf4c7ddbeac,0,0,0,0,0,NaN
28,20200806,MS,64400.0,418141.0,NaN,1184.0,4511.0,337.0,NaN,193.0,...,482541,21,39,e45ccec535c0130e1b56c1430384c3be57523d5d,0,0,0,0,0,NaN
29,20200806,MT,4602.0,181213.0,NaN,87.0,259.0,NaN,NaN,NaN,...,185815,0,11,025382837c0d2d655d076d801898c0257b1b2aac,0,0,0,0,0,NaN
30,20200806,NC,131267.0,1773483.0,NaN,1147.0,NaN,333.0,NaN,NaN,...,1904750,42,0,356bb1dbfbc093de9b92ad72bbd96919cb933311,0,0,0,0,0,NaN
31,20200806,ND,7177.0,156542.0,NaN,46.0,400.0,NaN,NaN,NaN,...,163719,2,6,9389fff0bffa30d33baace10b2e957e097c54169,0,0,0,0,0,NaN
32,20200806,NE,27489.0,262692.0,NaN,148.0,1681.0,NaN,NaN,NaN,...,290181,3,37,a4611cb191cb7de2961da8e549a3c66ce8980337,0,0,0,0,0,NaN
33,20200806,NH,6719.0,160688.0,NaN,20.0,698.0,NaN,209.0,NaN,...,167407,0,0,487fbbe28ca72136fa37a17e20b0e515993dee47,0,0,0,0,0,NaN
34,20200806,NJ,183701.0,2046544.0,NaN,754.0,21565.0,129.0,NaN,54.0,...,2230245,7,0,8a6e4f761a1738e1d254d4670fc7a7f02d84535a,0,0,0,0,0,NaN
35,20200806,NM,21566.0,575842.0,NaN,138.0,2781.0,NaN,NaN,NaN,...,597408,9,28,b3d52f5529ac9b95e8efbaafb0ae36a12dabfa01,0,0,0,0,0,NaN
36,20200806,NV,53557.0,446638.0,NaN,1117.0,NaN,307.0,NaN,208.0,...,500195,10,0,1d5c83e8ac0e04ad314f442735e2aa2a44c4564f,0,0,0,0,0,NaN
37,20200806,NY,418928.0,5879877.0,NaN,570.0,89995.0,132.0,NaN,69.0,...,6298805,6,0,61fe4a0b31a2ad7d7bcca3a65f58130855c11a75,0,0,0,0,0,NaN
38,20200806,OH,97471.0,1500568.0,NaN,979.0,11366.0,342.0,2627.0,182.0,...,1598039,22,135,d3b2fffa64df7db8ab5bb6e77e6369800ab346ad,0,0,0,0,0,NaN
39,20200806,OK,41401.0,633252.0,NaN,643.0,3497.0,216.0,NaN,NaN,...,674653,10,52,507d8bb53e17ae80ca29c0279c78623c87371952,0,0,0,0,0,NaN
40,20200806,OR,20225.0,412037.0,NaN,230.0,1743.0,58.0,NaN,29.0,...,432262,1,17,04e7270762f0b9939f89f7e3f85dc6e8e1d20c2b,0,0,0,0,0,NaN
41,20200806,PA,116521.0,1183730.0,NaN,663.0,NaN,NaN,NaN,98.0,...,1300251,38,0,cae882b531da23af4ef4d22a6995feee3231e17b,0,0,0,0,0,NaN
42,20200806,PR,19934.0,305972.0,NaN,456.0,NaN,76.0,NaN,53.0,...,325906,12,0,56209748ba4529127f294ef4b03d4f3b81072fe3,0,0,0,0,0,NaN
43,20200806,RI,19611.0,196112.0,NaN,83.0,2264.0,11.0,NaN,4.0,...,215723,2,16,79b6a90af33c61f59347f6df8e50fbbde4178d19,0,0,0,0,0,NaN
44,20200806,SC,96797.0,659348.0,NaN,1492.0,5799.0,356.0,NaN,276.0,...,756145,49,0,ab02e42f8c0f5040a6c6d99a2ed1cc89835da297,0,0,0,0,0,NaN
45,20200806,SD,9273.0,108301.0,NaN,44.0,861.0,NaN,NaN,NaN,...,117574,4,5,5a5ead14561ae9d6b388128b294343ecdf3060fb,0,0,0,0,0,NaN
46,20200806,TN,116350.0,1518841.0,NaN,1497.0,5109.0,NaN,NaN,NaN,...,1635191,42,108,88da51496f7f13861742220658f99e91cb2d46bc,0,0,0,0,0,NaN
47,20200806,TX,467485.0,3476995.0,NaN,8302.0,NaN,2917.0,NaN,NaN,...,3944480,306,0,26c937b04a8fc2e5759b9f4200f578ea46e2301a,0,0,0,0,0,NaN
48,20200806,UT,42915.0,512476.0,NaN,220.0,2554.0,80.0,657.0,NaN,...,555391,3,35,a1589509fef7ed43baa68ba03b30d2cdf1cfadd7,0,0,0,0,0,NaN
49,20200806,VA,95867.0,1099060.0,474.0,1349.0,13984.0,284.0,NaN,157.0,...,1194927,25,158,4b88912df33b9ee858a404be84e4f276f2b39a84,0,0,0,0,0,NaN
50,20200806,VI,501.0,9874.0,12.0,NaN,NaN,NaN,NaN,NaN,...,10375,1,0,48e8c88d364472dbd9a1a8e282ebb263abfd74b6,0,0,0,0,0,NaN
51,20200806,VT,1445.0,98607.0,NaN,6.0,NaN,NaN,NaN,NaN,...,100052,1,0,f6129e2c02430599ff47b6ce27e2d01c50dd1057,0,0,0,0,0,NaN
52,20200806,WA,60084.0,950107.0,NaN,426.0,5840.0,NaN,NaN,58.0,...,1010191,5,61,3ee310f09a9a2621f0af17d4f27f82cffa96edc2,0,0,0,0,0,NaN
53,20200806,WI,61985.0,961851.0,92.0,251.0,4881.0,104.0,927.0,NaN,...,1023836,8,55,f6d7294b5c4030aeadd23d5c8b65bf040246fcf2,0,0,0,0,0,NaN
54,20200806,WV,7277.0,300132.0,NaN,123.0,NaN,47.0,NaN,11.0,...,307409,0,0,ebf5f834f24f25065c7f848557a5cfe8de6e1bd3,0,0,0,0,0,NaN

In [8]:
stateSeries = deathsByState['state']
stateSeries = stateSeries[:55]
print(stateSeries)

0     AK
1     AL
2     AR
3     AS
4     AZ
5     CA
6     CO
7     CT
8     DC
9     DE
10    FL
11    GA
12    GU
13    HI
14    IA
15    ID
16    IL
17    IN
18    KS
19    KY
20    LA
21    MA
22    MD
23    ME
24    MI
25    MN
26    MO
27    MP
28    MS
29    MT
30    NC
31    ND
32    NE
33    NH
34    NJ
35    NM
36    NV
37    NY
38    OH
39    OK
40    OR
41    PA
42    PR
43    RI
44    SC
45    SD
46    TN
47    TX
48    UT
49    VA
50    VI
51    VT
52    WA
53    WI
54    WV
Name: state, dtype: object

## Psudo
Make List of States from original dataframe
Positive and Negative Cases is Cumulative by State, Need to get the increase/difference by date
Loop through States, 

Make loop for postivie total change by State
totalChangePositive.append(secondvalue - firstvalue) 

Make loop for negative total change by State
totalChangeNegative.append(secondvalue - firstvalue)

# >> Objective: 
Turn all 54 States into their own variables to hold a dataframe for covid over time by each state

# >> !
### Loop to put values into the variable in a list, 1st test assiging a value within each state from the list

In [9]:
count = 1
for i in stateSeries:
    globals()[i] = count
    count += 1

In [10]:
WA

53

# >> !
### Setup search params before loop of states

In [11]:
#Get correct conditional to select a specific states data from the frame
stateSeriesTime = deathsByState.loc[(deathsByState['state'] == 'WA')]

In [12]:
stateSeriesTime

,date,state,positive,negative,pending,hospitalizedCurrently,hospitalizedCumulative,inIcuCurrently,inIcuCumulative,onVentilatorCurrently,...,posNeg,deathIncrease,hospitalizedIncrease,hash,commercialScore,negativeRegularScore,negativeScore,positiveScore,score,grade
52,20200806,WA,60084.0,950107.0,NaN,426.0,5840.0,NaN,NaN,58.0,...,1010191,5,61,3ee310f09a9a2621f0af17d4f27f82cffa96edc2,0,0,0,0,0,NaN
108,20200805,WA,59379.0,950107.0,NaN,424.0,5779.0,NaN,NaN,47.0,...,1009486,19,35,43750ce59c62271fd6644efd972935231da714c5,0,0,0,0,0,NaN
164,20200804,WA,58715.0,950107.0,NaN,401.0,5744.0,NaN,NaN,52.0,...,1008822,4,52,29d891cedad1c26049d827822ecd21948802d52b,0,0,0,0,0,NaN
220,20200803,WA,58173.0,950107.0,NaN,401.0,5692.0,NaN,NaN,51.0,...,1008280,4,37,a3f5f5d8089a0308caa6239a92aac492c6b8b4e1,0,0,0,0,0,NaN
276,20200802,WA,57541.0,943987.0,NaN,407.0,5655.0,NaN,NaN,57.0,...,1001528,28,87,19d5d9436d5da7441cc3c98a124a68dd5d042363,0,0,0,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8636,20200126,WA,2.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,...,2,0,0,7acb526e14f20a29cc74a0b32a37328bc6eac6c2,0,0,0,0,0,NaN
8637,20200125,WA,2.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,...,2,0,0,9b52ca94dd2a996822542ea5f17a7363e7ad91cf,0,0,0,0,0,NaN
8638,20200124,WA,2.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,...,2,0,0,094154f68e74bfc30b977cdee888f9c07be4360e,0,0,0,0,0,NaN
8639,20200123,WA,2.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,...,2,0,0,e16af2a6a8f060355ff5ba499a28309a262c0b1e,0,0,0,0,0,NaN
8640,20200122,WA,2.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,...,2,0,0,8f8db794931706272489cddd51e917a4a69c8c9b,0,0,0,0,0,NaN

In [13]:
#setting this up if i need to add a letter to the iterator to create a new df of each state
alphaList = 'A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y, Z'

In [14]:
print(type(stateSeries))

<class 'pandas.core.series.Series'>

------------------------------------------------------------------------------------------------------------------

# >>!
Putting the two together// this should grab the last state from the loop because I havent set up
a second for loop to sub count with the state headers

In [18]:
count = stateSeries
for i in stateSeries:
    count = deathsByState.loc[(deathsByState['state'] == i)]
    globals()[i] = count

In [20]:
#Because count is being reassigned for every index it will have the last Index's values in the variable
count

,date,state,positive,negative,pending,hospitalizedCurrently,hospitalizedCumulative,inIcuCurrently,inIcuCumulative,onVentilatorCurrently,...,posNeg,deathIncrease,hospitalizedIncrease,hash,commercialScore,negativeRegularScore,negativeScore,positiveScore,score,grade
54,20200806,WV,7277.0,300132.0,NaN,123.0,NaN,47.0,NaN,11.0,...,307409,0,0,ebf5f834f24f25065c7f848557a5cfe8de6e1bd3,0,0,0,0,0,NaN
110,20200805,WV,7159.0,295435.0,NaN,115.0,NaN,47.0,NaN,13.0,...,302594,0,0,7cb6eec03573a432fda7ca97ef5bcd946851c51d,0,0,0,0,0,NaN
166,20200804,WV,7051.0,291388.0,NaN,111.0,NaN,40.0,NaN,14.0,...,298439,7,0,8f5c2560dec9094369d09a2d0445899f20b15fd1,0,0,0,0,0,NaN
222,20200803,WV,6973.0,288073.0,NaN,116.0,NaN,50.0,NaN,17.0,...,295046,0,0,fbca1fb5784a3d01552a51f88523437470d504c2,0,0,0,0,0,NaN
278,20200802,WV,6854.0,284358.0,NaN,112.0,NaN,47.0,NaN,16.0,...,291212,1,0,8036fc0e8eb44d8f0da330585a10d066c160204e,0,0,0,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8366,20200310,WV,0.0,2.0,3.0,NaN,NaN,NaN,NaN,NaN,...,2,0,0,c62198a1f3506c9535e316b001b1fb434bfcfea4,0,0,0,0,0,NaN
8416,20200309,WV,0.0,2.0,3.0,NaN,NaN,NaN,NaN,NaN,...,2,0,0,f466072417c42ef61834022612d5cf0b43c79c6d,0,0,0,0,0,NaN
8466,20200308,WV,0.0,2.0,3.0,NaN,NaN,NaN,NaN,NaN,...,2,0,0,4758d36cb0a8bbac1fa24ffbab1bdf6a79cab92a,0,0,0,0,0,NaN
8516,20200307,WV,0.0,2.0,3.0,NaN,NaN,NaN,NaN,NaN,...,2,0,0,20fba9c760b37162ddb2c3deb4556b9987338a04,0,0,0,0,0,NaN
8553,20200306,WV,0.0,1.0,4.0,NaN,NaN,NaN,NaN,NaN,...,1,0,0,273c09f1153e86f7df325ac20f42d5fb6a3be3d0,0,0,0,0,0,NaN

# ! Question 
How to Separate the original data without having to write separate .loc statements for each
conditional, ie to separate out each state

In [22]:
FL

,date,state,positive,negative,pending,hospitalizedCurrently,hospitalizedCumulative,inIcuCurrently,inIcuCumulative,onVentilatorCurrently,...,posNeg,deathIncrease,hospitalizedIncrease,hash,commercialScore,negativeRegularScore,negativeScore,positiveScore,score,grade
10,20200806,FL,510389.0,3346974.0,3325.0,7459.0,29515.0,NaN,NaN,NaN,...,3857363,120,559,5133c0415f2ad100e70476139a8b9e436006f4b6,0,0,0,0,0,NaN
66,20200805,FL,502739.0,3312145.0,3277.0,7615.0,28956.0,NaN,NaN,NaN,...,3814884,225,623,df3ca7e5b82e443c67bc254da0ec0233c8d8eb56,0,0,0,0,0,NaN
122,20200804,FL,497330.0,3287128.0,3280.0,7857.0,28333.0,NaN,NaN,NaN,...,3784458,247,589,1b31b1a08b39801931c5906c421002bd8e4ac9a9,0,0,0,0,0,NaN
178,20200803,FL,491884.0,3260914.0,3228.0,7938.0,27744.0,NaN,NaN,NaN,...,3752798,73,220,cb1200bf3ba3db8d3202aa4e724943524037bba4,0,0,0,0,0,NaN
234,20200802,FL,487132.0,3233865.0,3394.0,7952.0,27524.0,NaN,NaN,NaN,...,3720997,62,180,4226aafea9046160b5186e830453e60c65487f65,0,0,0,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8427,20200308,FL,17.0,118.0,108.0,NaN,NaN,NaN,NaN,NaN,...,135,0,0,3d2942aef7f73ad5a50a33896138a9403e50638d,0,0,0,0,0,NaN
8477,20200307,FL,14.0,100.0,88.0,NaN,NaN,NaN,NaN,NaN,...,114,0,0,914041890fd2c1e06a80fbbbd47f2289c9958968,0,0,0,0,0,NaN
8525,20200306,FL,9.0,55.0,51.0,NaN,NaN,NaN,NaN,NaN,...,64,0,0,a0172193d7cf2c1c45c672b3e64fa0a0b9ec807c,0,0,0,0,0,NaN
8558,20200305,FL,9.0,31.0,69.0,NaN,NaN,NaN,NaN,NaN,...,40,0,0,78051844675b3464a839fe95c5e0c40c0fd79ca1,0,0,0,0,0,NaN
8580,20200304,FL,2.0,24.0,16.0,NaN,NaN,NaN,NaN,NaN,...,26,0,0,b53d530bf94552ea4304fbfd2b4f20eacbb62dce,0,0,0,0,0,NaN

In [23]:
CA

,date,state,positive,negative,pending,hospitalizedCurrently,hospitalizedCumulative,inIcuCurrently,inIcuCumulative,onVentilatorCurrently,...,posNeg,deathIncrease,hospitalizedIncrease,hash,commercialScore,negativeRegularScore,negativeScore,positiveScore,score,grade
5,20200806,CA,529980.0,7970483.0,NaN,7485.0,NaN,2026.0,NaN,NaN,...,8500463,166,0,04d0f37534059d04347fd2c84c1183d80fe86371,0,0,0,0,0,NaN
61,20200805,CA,524722.0,7884678.0,NaN,7552.0,NaN,2005.0,NaN,NaN,...,8409400,202,0,c877f9c8b267330bc105adeffdf3dce664b3ba94,0,0,0,0,0,NaN
117,20200804,CA,519427.0,7786286.0,NaN,7630.0,NaN,2082.0,NaN,NaN,...,8305713,113,0,90e3e08ccbd077a1dd09f6322366feedef7d2356,0,0,0,0,0,NaN
173,20200803,CA,514901.0,7669795.0,NaN,7629.0,NaN,2069.0,NaN,NaN,...,8184696,32,0,3e13c19ce424ee3a196c2af8c24fa9df6cedf226,0,0,0,0,0,NaN
229,20200802,CA,509162.0,7526813.0,NaN,7761.0,NaN,2119.0,NaN,NaN,...,8035975,132,0,acaee9f7ca22b9c2c31866d7b2477e601fef5c3a,0,0,0,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8422,20200308,CA,88.0,462.0,NaN,NaN,NaN,NaN,NaN,NaN,...,550,0,0,841788a5ae11d1cb868b7d1a0b5dafbc665ba169,0,0,0,0,0,NaN
8472,20200307,CA,69.0,462.0,NaN,NaN,NaN,NaN,NaN,NaN,...,531,0,0,97d60a21e9065f4c8044c990091051b3f0c5a49c,0,0,0,0,0,NaN
8521,20200306,CA,60.0,462.0,NaN,NaN,NaN,NaN,NaN,NaN,...,522,0,0,662f66bd8d1c194ce87d7404753a9b83515d2695,0,0,0,0,0,NaN
8555,20200305,CA,53.0,462.0,NaN,NaN,NaN,NaN,NaN,NaN,...,515,0,0,8ee918675d3f2f0f6b94dee19267e2be366999ff,0,0,0,0,0,NaN
8579,20200304,CA,53.0,462.0,NaN,NaN,NaN,NaN,NaN,NaN,...,515,0,0,5a4090a5d0f48c63008d34430a1845a383bebc1f,0,0,0,0,0,NaN

In [24]:
NY

,date,state,positive,negative,pending,hospitalizedCurrently,hospitalizedCumulative,inIcuCurrently,inIcuCumulative,onVentilatorCurrently,...,posNeg,deathIncrease,hospitalizedIncrease,hash,commercialScore,negativeRegularScore,negativeScore,positiveScore,score,grade
37,20200806,NY,418928.0,5879877.0,NaN,570.0,89995.0,132.0,NaN,69.0,...,6298805,6,0,61fe4a0b31a2ad7d7bcca3a65f58130855c11a75,0,0,0,0,0,NaN
93,20200805,NY,418225.0,5808210.0,NaN,564.0,89995.0,134.0,NaN,69.0,...,6226435,4,0,f16995e7aabcaff873da5e93b8a73ad31635634b,0,0,0,0,0,NaN
149,20200804,NY,417589.0,5736178.0,NaN,568.0,89995.0,139.0,NaN,69.0,...,6153767,3,0,84b8716ddeb6ddfb438768ef19c62856846e73f3,0,0,0,0,0,NaN
205,20200803,NY,416843.0,5665931.0,NaN,536.0,89995.0,136.0,NaN,62.0,...,6082774,2,0,d34a46fc8547c1b30fcb63dc21256c4256878091,0,0,0,0,0,NaN
261,20200802,NY,416298.0,5614637.0,NaN,556.0,89995.0,143.0,NaN,71.0,...,6030935,6,0,cef9e33c1f6c3908cf41497cae4b3b0f4bfe4647,0,0,0,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8451,20200308,NY,105.0,92.0,NaN,NaN,NaN,NaN,NaN,NaN,...,197,0,0,fa2a693c8e7c1123ce6741af19746db86f9d8fce,0,0,0,0,0,NaN
8501,20200307,NY,76.0,92.0,236.0,NaN,NaN,NaN,NaN,NaN,...,168,0,0,0fc0bcee0b931ade7d5379ba6ea1bbcbac513630,0,0,0,0,0,NaN
8541,20200306,NY,33.0,92.0,236.0,NaN,NaN,NaN,NaN,NaN,...,125,0,0,6f6a5ab226e7632b2d5bda9d6acc6cbe9e29cd7e,0,0,0,0,0,NaN
8568,20200305,NY,22.0,76.0,24.0,NaN,NaN,NaN,NaN,NaN,...,98,0,0,24af0f3d698331d8a3896c0f921342be3b0817c0,0,0,0,0,0,NaN
8586,20200304,NY,6.0,48.0,24.0,NaN,NaN,NaN,NaN,NaN,...,54,0,0,ad9266331f3f338e9f1c22b2a522134f05f59243,0,0,0,0,0,NaN