In [28]:
import pandas as pd

In [40]:
deaths_from_covid=pd.read_csv("C:/Users/cynth/Desktop/GWU-Project-1/GWU-Project-1/data_resources/covid_death.csv")

In [41]:
deaths_from_covid.head()

,Data as of,Start week,End Week,State,Sex,Age group,COVID-19 Deaths,Total Deaths,Pneumonia Deaths,Pneumonia and COVID-19 Deaths,Influenza Deaths,"Pneumonia, Influenza, or COVID-19 Deaths",Footnote
0,8/5/2020,2/1/2020,8/1/2020,United States,All,Under 1 year,15.0,8832.0,82.0,2.0,14.0,109.0,NaN
1,8/5/2020,2/1/2020,8/1/2020,United States,All,1-4 years,10.0,1690.0,55.0,2.0,41.0,104.0,NaN
2,8/5/2020,2/1/2020,8/1/2020,United States,All,5-14 years,20.0,2611.0,86.0,6.0,50.0,150.0,NaN
3,8/5/2020,2/1/2020,8/1/2020,United States,All,15-24 years,225.0,16353.0,326.0,77.0,52.0,522.0,NaN
4,8/5/2020,2/1/2020,8/1/2020,United States,All,25-34 years,1074.0,33993.0,1250.0,477.0,150.0,1983.0,NaN

In [42]:
del deaths_from_covid['Footnote']

In [43]:
deaths_from_covid.head(15)

,Data as of,Start week,End Week,State,Sex,Age group,COVID-19 Deaths,Total Deaths,Pneumonia Deaths,Pneumonia and COVID-19 Deaths,Influenza Deaths,"Pneumonia, Influenza, or COVID-19 Deaths"
0,8/5/2020,2/1/2020,8/1/2020,United States,All,Under 1 year,15.0,8832.0,82.0,2.0,14.0,109.0
1,8/5/2020,2/1/2020,8/1/2020,United States,All,1-4 years,10.0,1690.0,55.0,2.0,41.0,104.0
2,8/5/2020,2/1/2020,8/1/2020,United States,All,5-14 years,20.0,2611.0,86.0,6.0,50.0,150.0
3,8/5/2020,2/1/2020,8/1/2020,United States,All,15-24 years,225.0,16353.0,326.0,77.0,52.0,522.0
4,8/5/2020,2/1/2020,8/1/2020,United States,All,25-34 years,1074.0,33993.0,1250.0,477.0,150.0,1983.0
5,8/5/2020,2/1/2020,8/1/2020,United States,All,35-44 years,2728.0,48090.0,2700.0,1152.0,242.0,4489.0
6,8/5/2020,2/1/2020,8/1/2020,United States,All,45-54 years,7299.0,89394.0,7066.0,3281.0,573.0,11553.0
7,8/5/2020,2/1/2020,8/1/2020,United States,All,55-64 years,17583.0,206614.0,19117.0,8177.0,1221.0,29527.0
8,8/5/2020,2/1/2020,8/1/2020,United States,All,65-74 years,29870.0,313626.0,32620.0,13853.0,1426.0,49832.0
9,8/5/2020,2/1/2020,8/1/2020,United States,All,75-84 years,37495.0,385341.0,41005.0,16899.0,1456.0,62857.0
10,8/5/2020,2/1/2020,8/1/2020,United States,All,85 years and over,45845.0,484400.0,45788.0,17963.0,1367.0,74866.0
11,8/5/2020,2/1/2020,8/1/2020,United States,All,All Ages,142164.0,1590944.0,150095.0,61889.0,6592.0,235992.0
12,8/5/2020,2/1/2020,8/1/2020,United States,Male,Under 1 year,9.0,4909.0,52.0,2.0,8.0,67.0
13,8/5/2020,2/1/2020,8/1/2020,United States,Male,1-4 years,5.0,991.0,28.0,1.0,25.0,57.0
14,8/5/2020,2/1/2020,8/1/2020,United States,Male,5-14 years,15.0,1550.0,44.0,6.0,22.0,75.0

In [44]:
unbin=[]
for ages in deaths_from_covid['Age group']:
    unbin.append(ages)
print(unbin)

['Under 1 year', '1-4 years', '5-14 years', '15-24 years', '25-34 years', '35-44 years', '45-54 years', '55-64 years', '65-74 years', '75-84 years', '85 years and over', 'All Ages', 'Under 1 year', '1-4 years', '5-14 years', '15-24 years', '25-34 years', '35-44 years', '45-54 years', '55-64 years', '65-74 years', '75-84 years', '85 years and over', 'All ages', 'Under 1 year', '1-4 years', '5-14 years', '15-24 years', '25-34 years', '35-44 years', '45-54 years', '55-64 years', '65-74 years', '75-84 years', '85 years and over', 'All ages', 'All ages', 'All Ages', 'Under 1 year', '1-4 years', '5-14 years', '15-24 years', '25-34 years', '35-44 years', '45-54 years', '55-64 years', '65-74 years', '75-84 years', '85 years and over', 'All ages', 'Under 1 year', '1-4 years', '5-14 years', '15-24 years', '25-34 years', '35-44 years', '45-54 years', '55-64 years', '65-74 years', '75-84 years', '85 years and over', 'All ages', 'All ages', 'All Ages', 'Under 1 year', '1-4 years', '5-14 years', '15-24 years', '25-34 years', '35-44 years', '45-54 years', '55-64 years', '65-74 years', '75-84 years', '85 years and over', 'All ages', 'Under 1 year', '1-4 years', '5-14 years', '15-24 years', '25-34 years', '35-44 years', '45-54 years', '55-64 years', '65-74 years', '75-84 years', '85 years and over', 'All ages', 'All ages', 'All Ages', 'Under 1 year', '1-4 years', '5-14 years', '15-24 years', '25-34 years', '35-44 years', '45-54 years', '55-64 years', '65-74 years', '75-84 years', '85 years and over', 'All ages', 'Under 1 year', '1-4 years', '5-14 years', '15-24 years', '25-34 years', '35-44 years', '45-54 years', '55-64 years', '65-74 years', '75-84 years', '85 years and over', 'All ages', 'All ages', 'All Ages', 'Under 1 year', '1-4 years', '5-14 years', '15-24 years', '25-34 years', '35-44 years', '45-54 years', '55-64 years', '65-74 years', '75-84 years', '85 years and over', 'All ages', 'Under 1 year', '1-4 years', '5-14 years', '15-24 years', '25-34 years', '35-44 years', '45-54 years', '55-64 years', '65-74 years', '75-84 years', '85 years and over', 'All ages', 'All ages', 'All Ages', 'Under 1 year', '1-4 years', '5-14 years', '15-24 years', '25-34 years', '35-44 years', '45-54 years', '55-64 years', '65-74 years', '75-84 years', '85 years and over', 'All ages', 'Under 1 year', '1-4 years', '5-14 years', '15-24 years', '25-34 years', '35-44 years', '45-54 years', '55-64 years', '65-74 years', '75-84 years', '85 years and over', 'All ages', 'All ages', 'All Ages', 'Under 1 year', '1-4 years', '5-14 years', '15-24 years', '25-34 years', '35-44 years', '45-54 years', '55-64 years', '65-74 years', '75-84 years', '85 years and over', 'All ages', 'Under 1 year', '1-4 years', '5-14 years', '15-24 years', '25-34 years', '35-44 years', '45-54 years', '55-64 years', '65-74 years', '75-84 years', '85 years and over', 'All ages', 'All ages', 'All Ages', 'Under 1 year', '1-4 years', '5-14 years', '15-24 years', '25-34 years', '35-44 years', '45-54 years', '55-64 years', '65-74 years', '75-84 years', '85 years and over', 'All ages', 'Under 1 year', '1-4 years', '5-14 years', '15-24 years', '25-34 years', '35-44 years', '45-54 years', '55-64 years', '65-74 years', '75-84 years', '85 years and over', 'All ages', 'All ages', 'All Ages', 'Under 1 year', '1-4 years', '5-14 years', '15-24 years', '25-34 years', '35-44 years', '45-54 years', '55-64 years', '65-74 years', '75-84 years', '85 years and over', 'All ages', 'Under 1 year', '1-4 years', '5-14 years', '15-24 years', '25-34 years', '35-44 years', '45-54 years', '55-64 years', '65-74 years', '75-84 years', '85 years and over', 'All ages', 'All ages', 'All Ages', 'Under 1 year', '1-4 years', '5-14 years', '15-24 years', '25-34 years', '35-44 years', '45-54 years', '55-64 years', '65-74 years', '75-84 years', '85 years and over', 'All ages', 'Under 1 year', '1-4 years', '5-14 years', '15-24 years', '25-34 years', '35-44 years', '45-54 years', '55-64 years', '65-74 years', '75-84 years', '85 years and over', 'All ages', 'All ages', 'All Ages', 'Under 1 year', '1-4 years', '5-14 years', '15-24 years', '25-34 years', '35-44 years', '45-54 years', '55-64 years', '65-74 years', '75-84 years', '85 years and over', 'All ages', 'Under 1 year', '1-4 years', '5-14 years', '15-24 years', '25-34 years', '35-44 years', '45-54 years', '55-64 years', '65-74 years', '75-84 years', '85 years and over', 'All ages', 'All ages', 'All Ages', 'Under 1 year', '1-4 years', '5-14 years', '15-24 years', '25-34 years', '35-44 years', '45-54 years', '55-64 years', '65-74 years', '75-84 years', '85 years and over', 'All ages', 'Under 1 year', '1-4 years', '5-14 years', '15-24 years', '25-34 years', '35-44 years', '45-54 years', '55-64 years', '65-74 years', '75-84 years', '85 years and over', 'All ages', 'All ages', 'All Ages', 'Under 1 year', '1-4 years', '5-14 years', '15-24 years', '25-34 years', '35-44 years', '45-54 years', '55-64 years', '65-74 years', '75-84 years', '85 years and over', 'All ages', 'Under 1 year', '1-4 years', '5-14 years', '15-24 years', '25-34 years', '35-44 years', '45-54 years', '55-64 years', '65-74 years', '75-84 years', '85 years and over', 'All ages', 'All ages', 'All Ages', 'Under 1 year', '1-4 years', '5-14 years', '15-24 years', '25-34 years', '35-44 years', '45-54 years', '55-64 years', '65-74 years', '75-84 years', '85 years and over', 'All ages', 'Under 1 year', '1-4 years', '5-14 years', '15-24 years', '25-34 years', '35-44 years', '45-54 years', '55-64 years', '65-74 years', '75-84 years', '85 years and over', 'All ages', 'All ages', 'All Ages', 'Under 1 year', '1-4 years', '5-14 years', '15-24 years', '25-34 years', '35-44 years', '45-54 years', '55-64 years', '65-74 years', '75-84 years', '85 years and over', 'All ages', 'Under 1 year', '1-4 years', '5-14 years', '15-24 years', '25-34 years', '35-44 years', '45-54 years', '55-64 years', '65-74 years', '75-84 years', '85 years and over', 'All ages', 'All ages', 'All Ages', 'Under 1 year', '1-4 years', '5-14 years', '15-24 years', '25-34 years', '35-44 years', '45-54 years', '55-64 years', '65-74 years', '75-84 years', '85 years and over', 'All ages', 'Under 1 year', '1-4 years', '5-14 years', '15-24 years', '25-34 years', '35-44 years', '45-54 years', '55-64 years', '65-74 years', '75-84 years', '85 years and over', 'All ages', 'All ages', 'All Ages', 'Under 1 year', '1-4 years', '5-14 years', '15-24 years', '25-34 years', '35-44 years', '45-54 years', '55-64 years', '65-74 years', '75-84 years', '85 years and over', 'All ages', 'Under 1 year', '1-4 years', '5-14 years', '15-24 years', '25-34 years', '35-44 years', '45-54 years', '55-64 years', '65-74 years', '75-84 years', '85 years and over', 'All ages', 'All ages', 'All Ages', 'Under 1 year', '1-4 years', '5-14 years', '15-24 years', '25-34 years', '35-44 years', '45-54 years', '55-64 years', '65-74 years', '75-84 years', '85 years and over', 'All ages', 'Under 1 year', '1-4 years', '5-14 years', '15-24 years', '25-34 years', '35-44 years', '45-54 years', '55-64 years', '65-74 years', '75-84 years', '85 years and over', 'All ages', 'All ages', 'All Ages', 'Under 1 year', '1-4 years', '5-14 years', '15-24 years', '25-34 years', '35-44 years', '45-54 years', '55-64 years', '65-74 years', '75-84 years', '85 years and over', 'All ages', 'Under 1 year', '1-4 years', '5-14 years', '15-24 years', '25-34 years', '35-44 years', '45-54 years', '55-64 years', '65-74 years', '75-84 years', '85 years and over', 'All ages', 'All ages', 'All Ages', 'Under 1 year', '1-4 years', '5-14 years', '15-24 years', '25-34 years', '35-44 years', '45-54 years', '55-64 years', '65-74 years', '75-84 years', '85 years and over', 'All ages', 'Under 1 year', '1-4 years', '5-14 years', '15-24 years', '25-34 years', '35-44 years', '45-54 years', '55-64 years', '65-74 years', '75-84 years', '85 years and over', 'All ages', 'All ages', 'All Ages', 'Under 1 year', '1-4 years', '5-14 years', '15-24 years', '25-34 years', '35-44 years', '45-54 years', '55-64 years', '65-74 years', '75-84 years', '85 years and over', 'All ages', 'Under 1 year', '1-4 years', '5-14 years', '15-24 years', '25-34 years', '35-44 years', '45-54 years', '55-64 years', '65-74 years', '75-84 years', '85 years and over', 'All ages', 'All ages', 'All Ages', 'Under 1 year', '1-4 years', '5-14 years', '15-24 years', '25-34 years', '35-44 years', '45-54 years', '55-64 years', '65-74 years', '75-84 years', '85 years and over', 'All ages', 'Under 1 year', '1-4 years', '5-14 years', '15-24 years', '25-34 years', '35-44 years', '45-54 years', '55-64 years', '65-74 years', '75-84 years', '85 years and over', 'All ages', 'All ages', 'All Ages', 'Under 1 year', '1-4 years', '5-14 years', '15-24 years', '25-34 years', '35-44 years', '45-54 years', '55-64 years', '65-74 years', '75-84 years', '85 years and over', 'All ages', 'Under 1 year', '1-4 years', '5-14 years', '15-24 years', '25-34 years', '35-44 years', '45-54 years', '55-64 years', '65-74 years', '75-84 years', '85 years and over', 'All ages', 'All ages', 'All Ages', 'Under 1 year', '1-4 years', '5-14 years', '15-24 years', '25-34 years', '35-44 years', '45-54 years', '55-64 years', '65-74 years', '75-84 years', '85 years and over', 'All ages', 'Under 1 year', '1-4 years', '5-14 years', '15-24 years', '25-34 years', '35-44 years', '45-54 years', '55-64 years', '65-74 years', '75-84 years', '85 years and over', 'All ages', 'All ages', 'All Ages', 'Under 1 year', '1-4 years', '5-14 years', '15-24 years', '25-34 years', '35-44 years', '45-54 years', '55-64 years', '65-74 years', '75-84 years', '85 years and over', 'All ages', 'Under 1 year', '1-4 years', '5-14 years', '15-24 years', '25-34 years', '35-44 years', '45-54 years', '55-64 years', '65-74 years', '75-84 years', '85 years and over', 'All ages', 'All ages', 'All Ages', 'Under 1 year', '1-4 years', '5-14 years', '15-24 years', '25-34 years', '35-44 years', '45-54 years', '55-64 years', '65-74 years', '75-84 years', '85 years and over', 'All ages', 'Under 1 year', '1-4 years', '5-14 years', '15-24 years', '25-34 years', '35-44 years', '45-54 years', '55-64 years', '65-74 years', '75-84 years', '85 years and over', 'All ages', 'All ages', 'All Ages', 'Under 1 year', '1-4 years', '5-14 years', '15-24 years', '25-34 years', '35-44 years', '45-54 years', '55-64 years', '65-74 years', '75-84 years', '85 years and over', 'All ages', 'Under 1 year', '1-4 years', '5-14 years', '15-24 years', '25-34 years', '35-44 years', '45-54 years', '55-64 years', '65-74 years', '75-84 years', '85 years and over', 'All ages', 'All ages', 'All Ages', 'Under 1 year', '1-4 years', '5-14 years', '15-24 years', '25-34 years', '35-44 years', '45-54 years', '55-64 years', '65-74 years', '75-84 years', '85 years and over', 'All ages', 'Under 1 year', '1-4 years', '5-14 years', '15-24 years', '25-34 years', '35-44 years', '45-54 years', '55-64 years', '65-74 years', '75-84 years', '85 years and over', 'All ages', 'All ages', 'All Ages', 'Under 1 year', '1-4 years', '5-14 years', '15-24 years', '25-34 years', '35-44 years', '45-54 years', '55-64 years', '65-74 years', '75-84 years', '85 years and over', 'All ages', 'Under 1 year', '1-4 years', '5-14 years', '15-24 years', '25-34 years', '35-44 years', '45-54 years', '55-64 years', '65-74 years', '75-84 years', '85 years and over', 'All ages', 'All ages', 'All Ages', 'Under 1 year', '1-4 years', '5-14 years', '15-24 years', '25-34 years', '35-44 years', '45-54 years', '55-64 years', '65-74 years', '75-84 years', '85 years and over', 'All ages', 'Under 1 year', '1-4 years', '5-14 years', '15-24 years', '25-34 years', '35-44 years', '45-54 years', '55-64 years', '65-74 years', '75-84 years', '85 years and over', 'All ages', 'All ages', 'All Ages', 'Under 1 year', '1-4 years', '5-14 years', '15-24 years', '25-34 years', '35-44 years', '45-54 years', '55-64 years', '65-74 years', '75-84 years', '85 years and over', 'All ages', 'Under 1 year', '1-4 years', '5-14 years', '15-24 years', '25-34 years', '35-44 years', '45-54 years', '55-64 years', '65-74 years', '75-84 years', '85 years and over', 'All ages', 'All ages', 'All Ages', 'Under 1 year', '1-4 years', '5-14 years', '15-24 years', '25-34 years', '35-44 years', '45-54 years', '55-64 years', '65-74 years', '75-84 years', '85 years and over', 'All ages', 'Under 1 year', '1-4 years', '5-14 years', '15-24 years', '25-34 years', '35-44 years', '45-54 years', '55-64 years', '65-74 years', '75-84 years', '85 years and over', 'All ages', 'All ages', 'All Ages', 'Under 1 year', '1-4 years', '5-14 years', '15-24 years', '25-34 years', '35-44 years', '45-54 years', '55-64 years', '65-74 years', '75-84 years', '85 years and over', 'All ages', 'Under 1 year', '1-4 years', '5-14 years', '15-24 years', '25-34 years', '35-44 years', '45-54 years', '55-64 years', '65-74 years', '75-84 years', '85 years and over', 'All ages', 'All ages', 'All Ages', 'Under 1 year', '1-4 years', '5-14 years', '15-24 years', '25-34 years', '35-44 years', '45-54 years', '55-64 years', '65-74 years', '75-84 years', '85 years and over', 'All ages', 'Under 1 year', '1-4 years', '5-14 years', '15-24 years', '25-34 years', '35-44 years', '45-54 years', '55-64 years', '65-74 years', '75-84 years', '85 years and over', 'All ages', 'All ages', 'All Ages', 'Under 1 year', '1-4 years', '5-14 years', '15-24 years', '25-34 years', '35-44 years', '45-54 years', '55-64 years', '65-74 years', '75-84 years', '85 years and over', 'All ages', 'Under 1 year', '1-4 years', '5-14 years', '15-24 years', '25-34 years', '35-44 years', '45-54 years', '55-64 years', '65-74 years', '75-84 years', '85 years and over', 'All ages', 'All ages', 'All Ages', 'Under 1 year', '1-4 years', '5-14 years', '15-24 years', '25-34 years', '35-44 years', '45-54 years', '55-64 years', '65-74 years', '75-84 years', '85 years and over', 'All ages', 'Under 1 year', '1-4 years', '5-14 years', '15-24 years', '25-34 years', '35-44 years', '45-54 years', '55-64 years', '65-74 years', '75-84 years', '85 years and over', 'All ages', 'All ages', 'All Ages', 'Under 1 year', '1-4 years', '5-14 years', '15-24 years', '25-34 years', '35-44 years', '45-54 years', '55-64 years', '65-74 years', '75-84 years', '85 years and over', 'All ages', 'Under 1 year', '1-4 years', '5-14 years', '15-24 years', '25-34 years', '35-44 years', '45-54 years', '55-64 years', '65-74 years', '75-84 years', '85 years and over', 'All ages', 'All ages', 'All Ages', 'Under 1 year', '1-4 years', '5-14 years', '15-24 years', '25-34 years', '35-44 years', '45-54 years', '55-64 years', '65-74 years', '75-84 years', '85 years and over', 'All ages', 'Under 1 year', '1-4 years', '5-14 years', '15-24 years', '25-34 years', '35-44 years', '45-54 years', '55-64 years', '65-74 years', '75-84 years', '85 years and over', 'All ages', 'All ages', 'All Ages', 'Under 1 year', '1-4 years', '5-14 years', '15-24 years', '25-34 years', '35-44 years', '45-54 years', '55-64 years', '65-74 years', '75-84 years', '85 years and over', 'All ages', 'Under 1 year', '1-4 years', '5-14 years', '15-24 years', '25-34 years', '35-44 years', '45-54 years', '55-64 years', '65-74 years', '75-84 years', '85 years and over', 'All ages', 'All ages', 'All Ages', 'Under 1 year', '1-4 years', '5-14 years', '15-24 years', '25-34 years', '35-44 years', '45-54 years', '55-64 years', '65-74 years', '75-84 years', '85 years and over', 'All ages', 'Under 1 year', '1-4 years', '5-14 years', '15-24 years', '25-34 years', '35-44 years', '45-54 years', '55-64 years', '65-74 years', '75-84 years', '85 years and over', 'All ages', 'All ages', 'All Ages', 'Under 1 year', '1-4 years', '5-14 years', '15-24 years', '25-34 years', '35-44 years', '45-54 years', '55-64 years', '65-74 years', '75-84 years', '85 years and over', 'All ages', 'Under 1 year', '1-4 years', '5-14 years', '15-24 years', '25-34 years', '35-44 years', '45-54 years', '55-64 years', '65-74 years', '75-84 years', '85 years and over', 'All ages', 'All ages', 'All Ages', 'Under 1 year', '1-4 years', '5-14 years', '15-24 years', '25-34 years', '35-44 years', '45-54 years', '55-64 years', '65-74 years', '75-84 years', '85 years and over', 'All ages', 'Under 1 year', '1-4 years', '5-14 years', '15-24 years', '25-34 years', '35-44 years', '45-54 years', '55-64 years', '65-74 years', '75-84 years', '85 years and over', 'All ages', 'All ages', 'All Ages', 'Under 1 year', '1-4 years', '5-14 years', '15-24 years', '25-34 years', '35-44 years', '45-54 years', '55-64 years', '65-74 years', '75-84 years', '85 years and over', 'All ages', 'Under 1 year', '1-4 years', '5-14 years', '15-24 years', '25-34 years', '35-44 years', '45-54 years', '55-64 years', '65-74 years', '75-84 years', '85 years and over', 'All ages', 'All ages', 'All Ages', 'Under 1 year', '1-4 years', '5-14 years', '15-24 years', '25-34 years', '35-44 years', '45-54 years', '55-64 years', '65-74 years', '75-84 years', '85 years and over', 'All ages', 'Under 1 year', '1-4 years', '5-14 years', '15-24 years', '25-34 years', '35-44 years', '45-54 years', '55-64 years', '65-74 years', '75-84 years', '85 years and over', 'All ages', 'All ages', 'All Ages', 'Under 1 year', '1-4 years', '5-14 years', '15-24 years', '25-34 years', '35-44 years', '45-54 years', '55-64 years', '65-74 years', '75-84 years', '85 years and over', 'All ages', 'Under 1 year', '1-4 years', '5-14 years', '15-24 years', '25-34 years', '35-44 years', '45-54 years', '55-64 years', '65-74 years', '75-84 years', '85 years and over', 'All ages', 'All ages', 'All Ages', 'Under 1 year', '1-4 years', '5-14 years', '15-24 years', '25-34 years', '35-44 years', '45-54 years', '55-64 years', '65-74 years', '75-84 years', '85 years and over', 'All ages', 'Under 1 year', '1-4 years', '5-14 years', '15-24 years', '25-34 years', '35-44 years', '45-54 years', '55-64 years', '65-74 years', '75-84 years', '85 years and over', 'All ages', 'All ages', 'All Ages', 'Under 1 year', '1-4 years', '5-14 years', '15-24 years', '25-34 years', '35-44 years', '45-54 years', '55-64 years', '65-74 years', '75-84 years', '85 years and over', 'All ages', 'Under 1 year', '1-4 years', '5-14 years', '15-24 years', '25-34 years', '35-44 years', '45-54 years', '55-64 years', '65-74 years', '75-84 years', '85 years and over', 'All ages', 'All ages', 'All Ages', 'Under 1 year', '1-4 years', '5-14 years', '15-24 years', '25-34 years', '35-44 years', '45-54 years', '55-64 years', '65-74 years', '75-84 years', '85 years and over', 'All ages', 'Under 1 year', '1-4 years', '5-14 years', '15-24 years', '25-34 years', '35-44 years', '45-54 years', '55-64 years', '65-74 years', '75-84 years', '85 years and over', 'All ages', 'All ages', 'All Ages', 'Under 1 year', '1-4 years', '5-14 years', '15-24 years', '25-34 years', '35-44 years', '45-54 years', '55-64 years', '65-74 years', '75-84 years', '85 years and over', 'All ages', 'Under 1 year', '1-4 years', '5-14 years', '15-24 years', '25-34 years', '35-44 years', '45-54 years', '55-64 years', '65-74 years', '75-84 years', '85 years and over', 'All ages', 'All ages', 'All Ages', 'Under 1 year', '1-4 years', '5-14 years', '15-24 years', '25-34 years', '35-44 years', '45-54 years', '55-64 years', '65-74 years', '75-84 years', '85 years and over', 'All ages', 'Under 1 year', '1-4 years', '5-14 years', '15-24 years', '25-34 years', '35-44 years', '45-54 years', '55-64 years', '65-74 years', '75-84 years', '85 years and over', 'All ages', 'All ages', 'All Ages', 'Under 1 year', '1-4 years', '5-14 years', '15-24 years', '25-34 years', '35-44 years', '45-54 years', '55-64 years', '65-74 years', '75-84 years', '85 years and over', 'All ages', 'Under 1 year', '1-4 years', '5-14 years', '15-24 years', '25-34 years', '35-44 years', '45-54 years', '55-64 years', '65-74 years', '75-84 years', '85 years and over', 'All ages', 'All ages', 'All Ages', 'Under 1 year', '1-4 years', '5-14 years', '15-24 years', '25-34 years', '35-44 years', '45-54 years', '55-64 years', '65-74 years',

In [45]:
deathAges = deaths_from_covid['Age group'].unique()
print(deathAges)

['Under 1 year' '1-4 years' '5-14 years' '15-24 years' '25-34 years'
 '35-44 years' '45-54 years' '55-64 years' '65-74 years' '75-84 years'
 '85 years and over' 'All Ages' 'All ages']

In [46]:
deathAges = deaths_from_covid['Age group']
for age in deathAges:
    deathAges = deathAges.replace('Under 1 year', 1)
    deathAges = deathAges.replace('1-4 years', (1+4)/2)
    deathAges = deathAges.replace('5-14 years', (5+14)/2)
    deathAges = deathAges.replace('15-24 years', (15+24)/2)
    deathAges = deathAges.replace('25-34 years', (25+34)/2)
    deathAges = deathAges.replace('35-44 years', (35+44)/2)
    deathAges = deathAges.replace('45-54 years', (45+54)/2)
    deathAges = deathAges.replace('55-64 years', (55+64)/2)
    deathAges = deathAges.replace('65-74 years', (65+74)/2)
    deathAges = deathAges.replace('75-84 years', (75+84)/2)
    deathAges = deathAges.replace('85 years and over', (85+100)/2)
    deathAges = deathAges.replace('All ages', 'NaN')
    deathAges = deathAges.replace('All Ages', 'NaN')
print(deathAges)

0          1
1        2.5
2        9.5
3       19.5
4       29.5
        ...
1411    79.5
1412    92.5
1413     NaN
1414     NaN
1415     NaN
Name: Age group, Length: 1416, dtype: object

In [47]:
deaths_from_covid["Ages of Death"] = deathAges

In [48]:
deaths_from_covid.head()

,Data as of,Start week,End Week,State,Sex,Age group,COVID-19 Deaths,Total Deaths,Pneumonia Deaths,Pneumonia and COVID-19 Deaths,Influenza Deaths,"Pneumonia, Influenza, or COVID-19 Deaths",Ages of Death
0,8/5/2020,2/1/2020,8/1/2020,United States,All,Under 1 year,15.0,8832.0,82.0,2.0,14.0,109.0,1
1,8/5/2020,2/1/2020,8/1/2020,United States,All,1-4 years,10.0,1690.0,55.0,2.0,41.0,104.0,2.5
2,8/5/2020,2/1/2020,8/1/2020,United States,All,5-14 years,20.0,2611.0,86.0,6.0,50.0,150.0,9.5
3,8/5/2020,2/1/2020,8/1/2020,United States,All,15-24 years,225.0,16353.0,326.0,77.0,52.0,522.0,19.5
4,8/5/2020,2/1/2020,8/1/2020,United States,All,25-34 years,1074.0,33993.0,1250.0,477.0,150.0,1983.0,29.5

In [49]:
deaths_from_covid = deaths_from_covid.dropna()

In [50]:
deaths_from_covid.tail()

,Data as of,Start week,End Week,State,Sex,Age group,COVID-19 Deaths,Total Deaths,Pneumonia Deaths,Pneumonia and COVID-19 Deaths,Influenza Deaths,"Pneumonia, Influenza, or COVID-19 Deaths",Ages of Death
1402,8/5/2020,2/1/2020,8/1/2020,Puerto Rico,Female,Under 1 year,0.0,32.0,0.0,0.0,0.0,0.0,1
1409,8/5/2020,2/1/2020,8/1/2020,Puerto Rico,Female,55-64 years,0.0,0.0,0.0,0.0,0.0,0.0,59.5
1410,8/5/2020,2/1/2020,8/1/2020,Puerto Rico,Female,65-74 years,0.0,0.0,0.0,0.0,0.0,0.0,69.5
1411,8/5/2020,2/1/2020,8/1/2020,Puerto Rico,Female,75-84 years,0.0,0.0,0.0,0.0,0.0,0.0,79.5
1412,8/5/2020,2/1/2020,8/1/2020,Puerto Rico,Female,85 years and over,0.0,0.0,0.0,0.0,0.0,0.0,92.5

In [52]:
median_age=deaths_from_covid['Ages of Death'].median()
median_age

59.5