In [1]:
import pandas as pd

In [6]:
df=pd.read_csv("C:/Users/cynth/Desktop/GWU-Project-1/GWU-Project-1/data_resources/covid_death.csv")
df.head()

,Data as of,Start week,End Week,State,Sex,Age group,COVID-19 Deaths,Total Deaths,Pneumonia Deaths,Pneumonia and COVID-19 Deaths,Influenza Deaths,"Pneumonia, Influenza, or COVID-19 Deaths",Footnote
0,8/5/2020,2/1/2020,8/1/2020,United States,All,Under 1 year,15.0,8832.0,82.0,2.0,14.0,109.0,NaN
1,8/5/2020,2/1/2020,8/1/2020,United States,All,1-4 years,10.0,1690.0,55.0,2.0,41.0,104.0,NaN
2,8/5/2020,2/1/2020,8/1/2020,United States,All,5-14 years,20.0,2611.0,86.0,6.0,50.0,150.0,NaN
3,8/5/2020,2/1/2020,8/1/2020,United States,All,15-24 years,225.0,16353.0,326.0,77.0,52.0,522.0,NaN
4,8/5/2020,2/1/2020,8/1/2020,United States,All,25-34 years,1074.0,33993.0,1250.0,477.0,150.0,1983.0,NaN